# Jekyll Theme
theme: jekyll-theme-chirpy
lang: en
timezone: Asia/Dubai

# SEO & Site Metadata
title: Alisha’s Cyber Blog
tagline: A technical blog where I document everything I learn about cybersecurity
description: >
  A personal blog where I share my journey into cybersecurity, tools I build, CTF writeups, and real-world hacking lessons.

url: "https://alishataibek.github.io"

github:
  username: alishataibek

social:
  name: Alisha Taibek
  email: alishataibek.work@email.com
  links:
    - https://github.com/alishataibek
    - https://www.linkedin.com/in/alisha-taibek

# Appearance
theme_mode:  # auto toggle (light/dark based on system preference)
avatar: /assets/img/avatar.png 
social_preview_image: /assets/img/social-preview.png 

# Blog Behavior
toc: true
paginate: 10
baseurl: ""

# Comments (optional – disabled for now)
comments:
  provider:

# Progressive Web App
pwa:
  enabled: true
  cache:
    enabled: true

# Kramdown (Markdown processor settings)
kramdown:
  footnote_backlink: "&#8617;&#xfe0e;"
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    block:
      line_numbers: true
      start_line: 1

# Collections and defaults
collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: false
      toc: true
      permalink: /posts/:title/

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - purgecss.js
  - "*.config.js"
  - "package*.json"

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/

